[package]
name = "picar-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'

[dependencies]
anyhow = "1.0"
async-std = {version = "1.10", features = ["attributes"]}
chrono = "0.4"
futures = "0.3"
kamadak-exif = "0.5"
structopt = "0.3.25"
