[package]
name = "picar-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'

[dependencies]
anyhow = "1.0"
chrono = "0.4"
futures = "0.3"
kamadak-exif = "0.5"
structopt = "0.3.25"
tokio = { version = "1.15.0", features = ["rt", "rt-multi-thread", "macros"] }
