[package]
name = "picar-rs"
version = "0.2.0"
edition = "2021"

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'   # or 'z' to optimize "aggressively" for size
lto = true
strip = true

[dependencies]
anyhow = "1.0"
chrono = "0.4"
futures = "0.3"
gflags = "0.3.10"
kamadak-exif = "0.5"
tokio = { version = "1.15.0", features = ["rt", "macros"] }
