[package]
name = "picar-rs"
version = "0.2.0"
edition = "2021"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'

[dependencies]
anyhow = "1.0"
chrono = "0.4"
futures = "0.3"
gflags = "0.3.10"
kamadak-exif = "0.5"
tokio = { version = "1.15.0", features = ["rt", "macros"] }
